api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /


logout:
    path: /logout

app:
    host:     "{subdomain}.totalblu.com"
    resource: "@AppBundle/Controller/"
    defaults:
        _controller: AppBundle:Dashboard:dashboard
  
site:
    resource: "@SiteBundle/Controller/"
    type:     annotation