api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    host:     "{subdomain}.totalblu.com"
    resource: "@AppBundle/Controller/"
    type:     annotation
  
site:
    host:     "totalblu.com"
    resource: "@SiteBundle/Controller/"
    type:     annotation