api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

mobile_homepage:
    path:     /
    host:     "{subdomain}.totalblu.com"
    defaults:
        _controller: AppBundle:Main:mobileHomepage
        subdomain: ryan
    requirements:
        subdomain: ryan|user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Register:register }
    
logout:
    path: /logout
