# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.tokens.action_listener:
        class: AppBundle\EventListener\TokenListener
        arguments: ['%tokens%']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
    # check_user_authorized:
    #     class: AppBundle\Dashboard
    #     arguments: ["@request_stack"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    # site_manager:
    #     class: AppBundle\Site\SiteManager
    #     class: AppBundle\Controller\CustomExceptionController
    #     arguments: ['@twig', '%kernel.debug%']

    # current_site_listener:
    #     class: AppBundle\EventListener\CurrentSiteListener
    #     arguments: ['@doctrine.orm.default_entity_manager', '@router', '@security.token_storage']
    #     tags: 
    #     - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # app.manager_voter:
    #     class: AppBundle\Security\ManagerVoter
    #     tags:
    #     - { name: security.voter }
    #     public: false